/* No payment processor, cloud sync or analytics. Sales stay on this device. */
'use strict';
const C = POSCore, Store = POSStore;
const $ = s => document.querySelector(s);
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const E = escapeHTML;
const fmt = n => new Intl.NumberFormat('cs-CZ', { style:'currency', currency:'CZK', maximumFractionDigits:n % 100 ? 2 : 0 }).format(n / 100);
const inputMoney = n => String(n / 100).replace('.', ',');
const date = d => new Date(d).toLocaleString('cs-CZ', {timeZone:'Europe/Prague', day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
const colors = {'Pivo':'#f1c986','Destiláty':'#b1bcf3','Nealko':'#8acbb6','Víno':'#dbabd6','Koktejly':'#efaa91','Likéry':'#b6c49f','Rumy':'#daba8b','Whisky':'#e2b46a','Brandy':'#e3aa9e','Teplé nápoje':'#c6ba91','Snacks':'#98b8df'};
let state, view = 'pos', current = 'bar', category = 'Pivo', query = '', toastTimer, submitting = false;
const getOrder = () => state.orders.find(x => x.id === current) || state.orders[0];
const btn = (label, action, cls = 'secondary', attrs = '') => `<button type="button" class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
function toast(message, bad = false) { const t = $('#toast'); t.textContent = message; t.className = `toast visible${bad ? ' bad' : ''}`; clearTimeout(toastTimer); toastTimer = setTimeout(() => t.className = 'toast', 4200); }
async function command(type, payload) {
  $('#save-state').textContent = 'Ukládám…';
  try { const response = await Store.command(type, payload); state = response.state; render(); return response.result; }
  catch (e) { $('#save-state').textContent = 'Změna nebyla uložena'; $('#save-state').classList.add('error'); throw e; }
}
function field(label, name, value = '', extra = '', full = false) { return `<label class="field${full ? ' full' : ''}">${label}<input name="${name}" value="${E(value)}" ${extra}></label>`; }
function showDialog(title, body, submit, label = 'Uložit', onDone) {
  window.paymentAbort?.abort();
  const d = $('#dialog'); if (d.open) d.close();
  $('#dialog-title').textContent = title; $('#dialog-body').innerHTML = body; $('#dialog-error').textContent = '';
  $('#dialog-submit').textContent = label; $('#dialog-submit').hidden = !submit; $('#dialog-submit').disabled = false;
  $('#dialog-form').onsubmit = async event => {
    event.preventDefault(); if (!submit || submitting) return;
    submitting = true; $('#dialog-submit').disabled = true; $('#dialog-error').textContent = '';
    try { const result = await submit(new FormData(event.currentTarget)); d.close(); if (onDone) await onDone(result); }
    catch (e) { if (d.open) $('#dialog-error').textContent = e.message || 'Operace se nepodařila.'; else toast(e.message || 'Operace se nepodařila.', true); }
    finally { submitting = false; $('#dialog-submit').disabled = false; }
  };
  d.showModal();
}
function connection() { const online = navigator.onLine; $('#network').textContent = online ? 'Připojeno' : 'Bez internetu'; $('#network').classList.toggle('offline', !online); }
function render() {
  if (!state) return;
  if (!state.orders.some(x => x.id === current)) current = 'bar';
  $('#venue').textContent = state.settings.venue;
  const sh = C.activeShift(state);
  $('#shift-label').textContent = sh ? `Směna od ${date(sh.openedAt)} · ${sh.operator}` : 'Směna není otevřená';
  $('#save-state').textContent = 'Uloženo v tomto zařízení'; $('#save-state').classList.remove('error');
  document.querySelectorAll('[data-view]').forEach(b => b.classList.toggle('active', b.dataset.view === view));
  const templates = { pos: renderPOS, history: renderHistory, overview: renderOverview, catalog: renderCatalog, settings: renderSettings };
  $('#app').innerHTML = templates[view]();
  if (view === 'pos') {
    renderProducts();
    $('#search').addEventListener('input', e => { query = e.target.value; document.querySelectorAll('.category').forEach(b => b.classList.toggle('active', !query && b.dataset.id===category)); renderProducts(); });
  }
  if (view === 'settings') $('#settings-form').onsubmit = async e => { e.preventDefault(); try { await command('settings', Object.fromEntries(new FormData(e.currentTarget))); toast('Nastavení uložené.'); } catch(err) { toast(err.message, true); } };
}
function renderPOS() {
  const o = getOrder(), sh = C.activeShift(state), activeProducts = state.products.filter(x => x.active), cats = ['Vše', ...new Set(activeProducts.map(x => x.category))];
  const accounts = state.orders.map((a, i) => `<button class="account ${a.id === o.id ? 'active' : ''}" data-action="account" data-id="${E(a.id)}" aria-pressed="${a.id === o.id}"><span class="account-number">${a.id === 'bar' ? '↗' : String(i).padStart(2,'0')}</span><span class="account-name">${E(a.name)}<span class="account-amount">${a.lines.length ? fmt(C.sum(a.lines)) : 'Prázdný účet'}</span></span></button>`).join('');
  const lines = o.lines.map(l => `<div class="line"><div class="line-top"><span>${E(l.name)}${l.serving ? `<small class="small"> · ${E(l.serving)}</small>` : ''}</span><strong>${fmt(l.price * l.quantity)}</strong></div><div class="line-bottom"><span>${fmt(l.price)} / ks</span><div class="quantity"><button data-action="minus" data-id="${E(l.id)}" aria-label="Odebrat ${E(l.name)}">−</button><span>${l.quantity}</span><button data-action="add" data-id="${E(l.productId)}" aria-label="Přidat ${E(l.name)}">+</button></div></div></div>`).join('');
  return `<div class="pos-layout"><aside class="accounts"><div class="section-label"><span class="eyebrow">Otevřené účty</span><span class="badge">${state.orders.filter(x => x.lines.length).length}</span></div>${accounts}${btn('+ Nový účet','newOrder','add-account')}<div class="sidebar-note"><strong>Večer pod kontrolou.</strong>Rozdělané účty se ukládají po každé změně.</div></aside><section class="catalog-area"><div class="workspace-heading"><div><h1>Co to bude?</h1><p>Vyber nápoj a přidej ho na účet.</p></div><span class="eyebrow small">${activeProducts.length} položek</span></div>${!sh ? `<div class="notice"><span>Začni směnu a zadej hotovost v pokladně.</span>${btn('Otevřít směnu','openShift','shift-start')}</div>` : ''}${activeProducts.some(x => x.price === null) ? `<div class="notice"><span>${activeProducts.filter(x => x.price === null).length} položek v dodaném ceníku nemá cenu. Doplníš ji klepnutím; ostatní už můžeš markovat.</span></div>` : ''}<div class="search"><span class="search-icon">⌕</span><label class="sr-only" for="search">Hledat v nápojích</label><input id="search" type="search" placeholder="Název nebo číslo z Agnisu…" autocomplete="off" value="${E(query)}"></div><div class="categories" aria-label="Kategorie">${cats.map(c => `<button class="category ${category === c ? 'active' : ''}" data-action="category" data-id="${E(c)}" aria-pressed="${category === c}">${E(c)}</button>`).join('')}</div><div class="products" id="products"></div></section><section class="receipt" aria-label="Aktuální účet"><div class="receipt-head"><div><h2>${E(o.name)}</h2><p>${o.lines.length ? 'Účet zůstává otevřený do zaplacení' : 'Připravený pro dalšího hosta'}</p></div><span class="receipt-number">${String(state.orders.indexOf(o)).padStart(2, '0')}</span></div><div class="receipt-items">${lines || `<div class="receipt-empty"><span>≡</span><p>Účet je zatím prázdný.<br>Přidej první nápoj.</p></div>`}</div><div class="receipt-bottom"><div class="receipt-meta"><span>${o.lines.reduce((n,l) => n+l.quantity,0)} ks na účtu</span>${o.id !== 'bar' && !o.lines.length ? btn('Smazat účet','deleteOrder','splitbutton') : '<span>Ceny v Kč</span>'}</div><div class="receipt-total"><span>K zaplacení</span><strong>${fmt(C.sum(o.lines))}</strong></div><div class="payment-buttons">${btn('Hotově','payCash','paycash', !sh || !o.lines.length ? 'disabled' : '')}${btn('Kartou','payCard','paycard', !sh || !o.lines.length ? 'disabled' : '')}</div>${btn('Rozdělit platbu / položky','paySplit','splitbutton', !sh || !o.lines.length ? 'disabled' : '')}</div></section></div>`;
}
function renderProducts() {
  const norm = s => s.toLocaleLowerCase('cs').normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  const products = state.products.filter(p => p.active && (query || category === 'Vše' || p.category === category) && norm(p.name+' '+p.serving+' '+(p.sourceCode||'')).includes(norm(query)));
  $('#products').innerHTML = products.map(p => `<button class="product" style="--category:${colors[p.category] || '#a5c99a'}" data-action="add" data-id="${E(p.id)}"><span class="product-cat">${E(p.category)}${p.sourceCode ? ` · #${E(p.sourceCode)}` : ''}</span><span class="product-name">${E(p.name)}</span>${p.serving ? `<span class="product-serving">${E(p.serving)}</span>` : ''}<span class="product-price ${p.price === null ? 'unset' : ''}">${p.price === null ? (p.priceNote ? E(p.priceNote) + ' · zadat cenu' : 'Doplnit cenu') : fmt(p.price)}</span><span class="product-plus">+</span></button>`).join('') + `<button class="product quick-product" data-action="newProduct"><span>+</span>Nová položka</button>`;
}
function renderHistory() {
  const rows = [...state.receipts].reverse().map(r => `<tr><td><strong>${E(r.number)}</strong><br><span class="muted small">${date(r.at)}</span></td><td>${E(r.orderName)}<br><span class="tag ${r.kind === 'refund' ? 'orange' : ''}">${r.kind === 'refund' ? 'Vratka' : 'Zaplaceno'}</span></td><td>${r.cash && r.card ? 'Kombinovaně' : r.card ? 'Karta' : 'Hotově'}</td><td class="amount">${fmt(r.total)}</td><td class="table-actions">${btn('Doklad','receipt','secondary',`data-id="${E(r.id)}"`)}${r.kind === 'sale' && r.shiftId === C.activeShift(state)?.id && !state.receipts.some(x => x.refundOf === r.id) ? btn('Vratka','refund','textbutton',`data-id="${E(r.id)}"`) : ''}</td></tr>`).join('');
  return `<section class="page"><div class="workspace-heading"><div><h1>Doklady</h1><p>Prodeje a vratky z tohoto zařízení.</p></div>${btn('Export CSV','csv')}</div><div class="table-wrap"><table><thead><tr><th>Číslo / čas</th><th>Účet</th><th>Úhrada</th><th class="amount">Částka</th><th></th></tr></thead><tbody>${rows || '<tr><td colspan="5" class="empty">Zatím žádná platba. Doklady se objeví po zaplacení prvního účtu.</td></tr>'}</tbody></table></div></section>`;
}
function renderOverview() {
  const sh = C.activeShift(state), t = sh ? C.totals(state, sh.id) : {total:0,cash:0,card:0,count:0,expected:0,opening:0,movements:0};
  return `<section class="page"><div class="workspace-heading"><div><h1>${sh ? 'Dnešní směna' : 'Přehled směn'}</h1><p>${sh ? `Otevřeno ${date(sh.openedAt)} · ${E(sh.operator)}` : 'Otevři směnu a začni markovat.'}</p></div>${sh ? btn('Uzavřít směnu','closeShift','primary') : btn('Otevřít směnu','openShift','primary')}</div><div class="cards"><div class="stat lime"><span class="eyebrow">Tržba po vratkách</span><strong>${fmt(t.total)}</strong></div><div class="stat"><span class="eyebrow">Hotovostní tržba</span><strong>${fmt(t.cash)}</strong></div><div class="stat"><span class="eyebrow">Karetní tržba</span><strong>${fmt(t.card)}</strong></div><div class="stat"><span class="eyebrow">Počet prodejů</span><strong>${t.count}</strong></div></div>${sh ? `<div class="panel"><h3>Hotovost v pokladně</h3><div class="summary-row"><span class="muted">Počáteční vklad</span><strong>${fmt(t.opening)}</strong></div><div class="summary-row"><span class="muted">Vklady a výběry</span><strong>${fmt(t.movements)}</strong></div><div class="summary-row"><span class="muted">Očekávaná hotovost</span><strong>${fmt(t.expected)}</strong></div><div class="actions section-gap">${btn('Vklad / výběr','cashMovement')}${btn('Export CSV','csv')}${btn('Stáhnout zálohu','backup')}</div>${sh.movements.length ? `<div class="section-gap">${sh.movements.map(x => `<div class="summary-row small"><span>${date(x.at)} · ${E(x.reason)}</span><span>${fmt(x.amount)}</span></div>`).join('')}</div>` : ''}</div>` : ''}<div class="panel"><h3>Uzavřené směny</h3>${state.shifts.filter(x => x.closedAt).reverse().map(x => `<div class="summary-row"><span>${date(x.openedAt)} → ${date(x.closedAt)}<br><small class="muted">Hotovost: ${fmt(x.counted)} · rozdíl ${fmt(x.difference)}</small></span><strong>${fmt(x.summary.total)}</strong></div>`).join('') || '<p>Uzávěrky se tu zobrazí po skončení první směny.</p>'}</div></section>`;
}
function renderCatalog() {
  return `<section class="page"><div class="workspace-heading"><div><h1>Nápojový lístek</h1><p>Ceny se do otevřených účtů zpětně nepřepisují.</p></div><div class="actions">${btn('Hromadně vložit','bulkProducts')}${btn('+ Nová položka','newProduct','primary')}</div></div><div class="table-wrap"><table><thead><tr><th>Položka</th><th>Kategorie</th><th>Porce</th><th class="amount">Cena</th><th></th></tr></thead><tbody>${state.products.filter(x => x.active).map(p => `<tr><td><strong>${E(p.name)}</strong>${p.sourceCode ? `<br><span class="muted small">Agnis #${E(p.sourceCode)}</span>` : ''}</td><td>${E(p.category)}</td><td>${E(p.serving) || '—'}</td><td class="amount">${p.price === null ? '<span class="tag orange">Chybí cena</span>' : fmt(p.price)}</td><td class="table-actions">${btn('Upravit','editProduct','secondary',`data-id="${E(p.id)}"`)}${btn('Skrýt','archiveProduct','textbutton',`data-id="${E(p.id)}"`)}</td></tr>`).join('')}</tbody></table></div></section>`;
}
function renderSettings() {
  const s = state.settings;
  return `<section class="page"><div class="workspace-heading"><div><h1>Nastavení pokladny</h1><p>Údaje provozovatele, tisk a zálohy.</p></div></div><form id="settings-form" class="panel"><h3>Údaje na dokladu</h3><div class="form-grid">${field('Název podniku','venue',s.venue,'required maxlength="120"')}${field('Jméno obsluhy','operator',s.operator,'required maxlength="120"')}${field('Provozovatel / firma','company',s.company,'maxlength="120"')}${field('Adresa provozovny','address',s.address,'maxlength="240"')}${field('IČ','ico',s.ico,'maxlength="30"')}${field('DIČ','dic',s.dic,'maxlength="30"')}<label class="field full">Režim DPH<select name="vat"><option value="unknown" ${s.vat==='unknown'?'selected':''}>Zatím nenastaveno — provozní záznam bez rozpisu DPH</option><option value="nonpayer" ${s.vat==='nonpayer'?'selected':''}>Neplátce DPH</option><option value="payer" ${s.vat==='payer'?'selected':''}>Plátce DPH — sazbu nastavím u každé položky</option></select></label></div><div class="form-actions"><button type="submit" class="primary">Uložit údaje</button></div></form><div class="panel"><h3>Zálohy a přenos dat</h3><p>Účty a tržby jsou uložené jen v tomto prohlížeči na tomto zařízení. Mezi PC a telefonem se zatím nesdílejí. Používej stejnou adresu a běžné okno prohlížeče; smazání dat webu smaže i pokladnu.</p><p class="section-gap">Zálohu JSON stáhni po směně. Obnovit ji můžeš v prázdné pokladně. Při přechodu na jiné zařízení přestaň markovat na původním.</p><div class="form-actions">${btn('Stáhnout úplnou zálohu','backup','primary')}${btn('Obnovit ze zálohy','restore')}${btn('Prodeje do CSV','csv')}</div><p class="section-gap small">Poslední vytvořená záloha: ${state.lastBackup ? date(state.lastBackup) : 'zatím žádná'}</p></div><div class="panel"><h3>Tisk a karetní terminál</h3><p>Doklad se tiskne přes tiskový dialog prohlížeče. Pro pokladní tiskárnu zvol papír 80 mm a vypni záhlaví a zápatí. Platbu kartou provedeš na terminálu a teprve po jejím úspěchu ji potvrdíš v pokladně.</p></div><div class="panel"><h3>PUB-BIZZ · další propojení</h3><p>Export zálohy obsahuje stabilní identifikátory položek, prodejů a směn pro další napojení na PUB GURU. Automatický odpis skladu ani synchronizace s ostatními moduly zatím nejsou zapnuté.</p><p class="section-gap small">Pokladna ${E(state.deviceId.slice(0,8).toUpperCase())} · ${state.audit.length} záznamů historie změn</p></div></section>`;
}
function openShift() {
  showDialog('Otevřít směnu', `<p class="help">Kolik hotovosti je teď v zásuvce? Započítá se do kontroly uzávěrky.</p><div class="form-grid">${field('Počáteční hotovost (Kč)','opening','','required inputmode="decimal" placeholder="0"')}${field('Obsluha','operator',state.settings.operator,'required maxlength="120"')}</div>`, async f => {
    const r = await command('openShift', {opening:C.money(f.get('opening')),operator:f.get('operator')});
    navigator.storage?.persist?.().catch(() => {}); return r;
  }, 'Otevřít směnu', () => toast('Směna je otevřená.'));
}
function editProduct(id, addAfter = false) {
  const p = state.products.find(x => x.id === id) || {name:'',category:category !== 'Vše' ? category : 'Destiláty',serving:'',price:null,vatRate:null,stockProductId:''};
  showDialog(p.id ? 'Upravit položku' : 'Nová položka', `<div class="form-grid">${field('Název','name',p.name,'required maxlength="120"',true)}${field('Cena v Kč','price',p.price === null ? '' : inputMoney(p.price),'required inputmode="decimal" placeholder="Zadej skutečnou cenu"')}${field('Velikost porce','serving',p.serving,'maxlength="40" placeholder="např. 0,04 l"')}<label class="field">Kategorie<input name="category" list="category-list" value="${E(p.category)}" maxlength="40" required><datalist id="category-list">${['Pivo','Destiláty','Nealko','Víno','Koktejly','Káva','Ostatní'].map(x=>`<option>${x}</option>`).join('')}</datalist></label>${field('Sazba DPH (%)','vatRate',p.vatRate ?? '',`type="number" min="0" max="100" step="0.01" ${state.settings.vat === 'payer' ? 'required' : ''} placeholder="Nezadáno"`)}</div>`, async f => {
    const pr = await command('product', {id:p.id,name:f.get('name'),category:f.get('category'),price:C.money(f.get('price')),serving:f.get('serving'),vatRate:f.get('vatRate') === '' ? null : Number(f.get('vatRate')),stockProductId:p.stockProductId});
    return pr;
  }, addAfter && C.activeShift(state) ? 'Uložit a přidat na účet' : 'Uložit položku', async pr => { if (addAfter && C.activeShift(state)) await command('addLine',{orderId:current,productId:pr.id}); toast('Položka uložená.'); });
}
function pay(mode) {
  const o = structuredClone(getOrder()); if (!o.lines.length) return;
  const operationId = crypto.randomUUID(); const total = C.sum(o.lines); const startingCash = mode==='cash' ? Math.round(total/100)*100 : 0;
  const selected = () => o.lines.map(l => ({id:l.id,quantity:Number($('#dialog-form').elements['line-'+l.id].value)})).filter(x=>x.quantity>0);
  showDialog(mode === 'cash' ? 'Zaplatit hotově' : mode === 'card' ? 'Zaplatit kartou' : 'Rozdělit platbu', `<p class="help">Pro částečné placení uprav počet kusů. Zbytek zůstane na účtu.</p><div>${o.lines.map(l=>`<label class="selected-line"><span>${E(l.name)} ${E(l.serving)}<small>${fmt(l.price)} za kus</small></span><input aria-label="Zaplatit kusů ${E(l.name)}" type="number" name="line-${E(l.id)}" value="${l.quantity}" min="0" max="${l.quantity}" step="1" required></label>`).join('')}</div><div class="payment-summary" id="payment-summary"></div><div class="form-grid">${mode==='split'?field('Z toho hotově (Kč)','splitCash','0','required inputmode="decimal"'):''}${mode!=='card'?field('Přijato v hotovosti (Kč)','received',inputMoney(startingCash),'required inputmode="decimal"'):''}</div>${mode!=='cash'?'<label class="inline-check"><input type="checkbox" name="cardConfirmed" required>Platba kartou na terminálu proběhla úspěšně.</label>':''}`, async f => {
    for (const l of o.lines) { const q = Number(f.get('line-'+l.id)); if (!Number.isSafeInteger(q) || q<0 || q>l.quantity) throw new Error('Neplatný počet kusů.'); }
    return await command('checkout',{orderId:o.id,revision:o.revision,operationId,selected:selected(),mode,received:mode==='card'?0:C.money(f.get('received')),splitCash:mode==='split'?C.money(f.get('splitCash')):0,cardConfirmed:f.has('cardConfirmed')});
  }, 'Potvrdit zaplacení', r => { toast(`Uloženo · ${r.number}`); receiptDialog(r); });
  function preview() {
    try {
      const lines = C.selectedLines(o,selected()), raw=C.sum(lines), f=new FormData($('#dialog-form'));
      const cash = mode==='cash'?Math.round(raw/100)*100:mode==='split'?C.money(f.get('splitCash')):0;
      const received = mode==='card'?0:C.money(f.get('received'));
      const p=C.payment(raw,mode,Math.max(cash,received),cash);
      const cardCheck = $('#dialog-form').elements.cardConfirmed;
      if (cardCheck) { cardCheck.required = p.card > 0; cardCheck.closest('label').hidden = p.card === 0; }
      $('#payment-summary').innerHTML=`<div class="summary-row total"><span>K úhradě</span><strong>${fmt(p.total)}</strong></div>${p.rounding?`<div class="summary-row"><span>Zaokrouhlení</span><span>${fmt(p.rounding)}</span></div>`:''}${mode==='split'?`<div class="summary-row"><span>Na terminálu</span><strong>${fmt(p.card)}</strong></div>`:''}${mode!=='card'?`<div class="summary-row"><span>${received<cash?'Ještě chybí':'Vrátit hostovi'}</span><strong>${fmt(Math.abs(received-cash))}</strong></div>`:'<span class="muted small">Částku zadej na samostatném terminálu.</span>'}`;
    } catch(e) { $('#payment-summary').textContent=e.message; }
  }
  $('#dialog-body').addEventListener('input',preview,{signal:(window.paymentAbort?.abort(),window.paymentAbort=new AbortController()).signal});
  preview();
}
function receiptHTML(r) {
  const s=r.settings, sign=r.kind==='refund'?-1:1, vat={};
  for(const l of r.lines){if(l.vatRate!==null){const key=String(l.vatRate); const gross=l.price*l.quantity*sign; const tax=Math.round(gross*l.vatRate/(100+l.vatRate)); const v=vat[key]||(vat[key]={base:0,tax:0}); v.base+=gross-tax;v.tax+=tax;}}
  return `<div class="receipt-preview"><header><h3>${E(s.venue)}</h3>${s.company?`<div>${E(s.company)}</div>`:''}${s.address?`<div>${E(s.address)}</div>`:''}${s.ico?`<div>IČ: ${E(s.ico)}${s.dic?' · DIČ: '+E(s.dic):''}</div>`:''}<div class="section-gap">${r.kind==='refund'?'VRATKA':'PRODEJNÍ DOKLAD'} ${E(r.number)}</div><div>${date(r.at)} · ${E(r.operator)}</div><div>${E(r.orderName)}</div></header><hr><table><tbody>${r.lines.map(l=>`<tr><td>${l.quantity}× ${E(l.name)} ${E(l.serving)}<br><span class="muted">${fmt(l.price)} / ks</span></td><td class="amount">${fmt(l.price*l.quantity*sign)}</td></tr>`).join('')}</tbody></table><hr>${r.rounding?`<div class="summary-row"><span>Zaokrouhlení</span><span>${fmt(r.rounding)}</span></div>`:''}<div class="summary-row total"><span>Celkem</span><strong>${fmt(r.total)}</strong></div>${r.cash?`<div class="summary-row"><span>Hotově</span><span>${fmt(r.cash)}</span></div>`:''}${r.card?`<div class="summary-row"><span>Kartou</span><span>${fmt(r.card)}</span></div>`:''}${r.change?`<div class="summary-row"><span>Přijato / vráceno</span><span>${fmt(r.received)} / ${fmt(r.change)}</span></div>`:''}${s.vat==='payer'?`<hr>${Object.entries(vat).map(([rate,v])=>`<div class="small">DPH ${E(rate)} % · základ ${fmt(v.base)} · daň ${fmt(v.tax)}</div>`).join('')}`:''}${r.reason?`<p class="section-gap">Důvod vratky: ${E(r.reason)}</p>`:''}<div class="footnote">${s.vat==='unknown'?'Provozní záznam — režim DPH není nastaven.':s.vat==='nonpayer'?'Provozovatel není plátcem DPH.':''}${!s.company||!s.ico||!s.address?'<br>Údaje provozovatele nejsou kompletní.':''}<br>PUB-BIZZ · Děkujeme za návštěvu.</div></div>`;
}
function receiptDialog(r) { showDialog(r.kind==='refund'?'Vratka uložená':'Zaplaceno',receiptHTML(r),async()=>{ $('#print-area').innerHTML=receiptHTML(r); window.print(); },'Vytisknout doklad'); }
function download(name,content,type){ const url=URL.createObjectURL(new Blob([content],{type})); const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000); }
async function backup(){ const s=await Store.read(); const data=JSON.stringify(s); const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(data)))).map(x=>x.toString(16).padStart(2,'0')).join(''); const stamp=new Date().toISOString().replace(/[:.]/g,'-');download(`PUB-BIZZ-zaloha-${stamp}.json`,JSON.stringify({format:'pubbizz.pos.backup.v1',hash,data:s},null,2),'application/json');await command('backup',{});toast('Záloha připravená ke stažení.'); }
function csv(){
  const cell=v=>{let s=String(v??''); if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};
  const rows=[['doklad','datum','typ','ucet','polozka','porce','pocet','cena_kc','celkem_polozka_kc','dph_procent','doklad_hotove_kc','doklad_karta_kc','doklad_zaokrouhleni_kc','směna_id','produkt_id','sklad_id']];
  for(const r of state.receipts)r.lines.forEach((l,i)=>rows.push([r.number,r.at,r.kind,r.orderName,l.name,l.serving,l.quantity*(r.kind==='refund'?-1:1),inputMoney(l.price),inputMoney(l.price*l.quantity*(r.kind==='refund'?-1:1)),l.vatRate??'',i===0?inputMoney(r.cash):'',i===0?inputMoney(r.card):'',i===0?inputMoney(r.rounding):'',r.shiftId,l.productId,l.stockProductId]));
  download(`PUB-BIZZ-prodeje-${new Date().toISOString().slice(0,10)}.csv`,'\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8');toast('CSV připravené ke stažení.');
}
function closeShift(){ const sh=C.activeShift(state);if(!sh)return;if(state.orders.some(x=>x.lines.length)){toast('Nejdřív zaplať všechny rozdělané účty.',true);return;}const t=C.totals(state,sh.id);showDialog('Uzavřít směnu',`<div class="payment-summary"><div class="summary-row"><span>Tržba</span><strong>${fmt(t.total)}</strong></div><div class="summary-row"><span>Očekávaná hotovost</span><strong>${fmt(t.expected)}</strong></div></div>${field('Spočítaná hotovost v zásuvce (Kč)','counted','','required inputmode="decimal"')}<p class="help section-gap">Směna se uzamkne. Doklady zůstanou uložené a stáhne se úplná záloha.</p>`,f=>command('closeShift',{counted:C.money(f.get('counted'))}),'Uzavřít a zálohovat',async()=>{view='overview';render();await backup();});}
function bulkProducts(){showDialog('Hromadně vložit ceník',`<p class="help">Každý řádek: <strong>název; cena; kategorie; porce; DPH</strong>. Poslední tři údaje lze vynechat. Existující položky se shodným názvem a porcí se aktualizují.</p><label class="field">Položky<textarea name="rows" rows="9" required placeholder="Název nápoje; cena v Kč; kategorie; porce; DPH %"></textarea></label>`,async f=>{const rows=String(f.get('rows')).split(/\r?\n/).filter(x=>x.trim());if(rows.length>300)throw new Error('Najednou lze vložit nejvýš 300 položek.');const items=rows.map((row,i)=>{const [name,price,category='Ostatní',serving='',rate='']=row.split(';').map(x=>x.trim());if(!name||!price)throw new Error(`Na řádku ${i+1} chybí název nebo cena.`);return {name,price:C.money(price),category,serving,vatRate:rate===''?null:Number(rate.replace(',','.'))};});await command('importProducts',{items});},'Uložit ceník',()=>toast('Ceník byl uložený.'));}
const actions={
  account:async id=>{current=id;render();},category:async id=>{category=id;query='';render();},openShift,
  newOrder:()=>showDialog('Nový účet',field('Stůl nebo jméno hosta','name','','required maxlength="120" placeholder="např. Stůl 1 / Petr"'),f=>command('newOrder',{name:f.get('name')}),'Vytvořit účet',r=>{current=r.id;render();}),
  deleteOrder:async()=>{await command('deleteOrder',{orderId:current});current='bar';render();},
  add:async id=>{const p=state.products.find(x=>x.id===id);if(!p)return;if(p.price===null){editProduct(id,true);return;}if(!C.activeShift(state)){openShift();return;}await command('addLine',{orderId:current,productId:id});},
  minus:id=>showDialog('Odebrat jeden kus',field('Důvod opravy','reason','Oprava namarkování','required maxlength="120"'),f=>command('removeLine',{orderId:current,lineId:id,reason:f.get('reason')}),'Odebrat kus'),
  newProduct:()=>editProduct(),editProduct:id=>editProduct(id),archiveProduct:id=>showDialog('Skrýt položku',`<p class="help">${E(state.products.find(x=>x.id===id)?.name)} zmizí z nabídky. Existující účty a doklady zůstanou.</p>`,()=>command('archiveProduct',{id}),'Skrýt'),
  payCash:()=>pay('cash'),payCard:()=>pay('card'),paySplit:()=>pay('split'),
  receipt:id=>receiptDialog(state.receipts.find(x=>x.id===id)),
  refund:id=>{const r=state.receipts.find(x=>x.id===id);showDialog('Vrátit celý doklad',`<p class="help">Doklad ${E(r.number)} · ${fmt(r.total)}. Vrací se stejným způsobem jako původní platba. Vratka se uloží samostatně.</p>${field('Důvod vratky','reason','','required maxlength="120"')}${r.card?'<label class="inline-check"><input type="checkbox" name="cardConfirmed" required>Vrácení karetní platby na terminálu proběhlo.</label>':''}`,f=>command('refund',{receiptId:id,reason:f.get('reason'),cardConfirmed:f.has('cardConfirmed')}),'Zapsat vratku',receiptDialog);},
  cashMovement:()=>showDialog('Vklad / výběr hotovosti',`<div class="form-grid"><label class="field">Pohyb<select name="direction"><option value="1">Vklad do pokladny</option><option value="-1">Výběr z pokladny</option></select></label>${field('Částka v Kč','amount','','required inputmode="decimal"')}${field('Důvod','reason','','required maxlength="120"',true)}</div>`,f=>command('cashMovement',{amount:C.money(f.get('amount'))*Number(f.get('direction')),reason:f.get('reason')}),'Zapsat pohyb'),
  closeShift,backup,csv,bulkProducts,restore:()=>$('#restore-input').click()
};
document.addEventListener('click',async e=>{
  const close=e.target.closest('.close-dialog');if(close){if(!submitting)$('#dialog').close();return;}
  const tab=e.target.closest('[data-view]');if(tab){view=tab.dataset.view;render();return;}
  const b=e.target.closest('[data-action]');if(!b||b.disabled||!state)return;
  const action=actions[b.dataset.action];if(action)try{await action(b.dataset.id);}catch(err){toast(err.message||'Operace se nepodařila.',true);}
});
$('#dialog').addEventListener('cancel',e=>{if(submitting)e.preventDefault();});
$('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('Na telefonu přidej pokladnu na plochu z nabídky prohlížeče.');}catch{toast('Prohlížeč celoobrazovkový režim nepovolil.',true);}});
$('#restore-input').addEventListener('change',async e=>{
  const file=e.target.files?.[0];e.target.value='';if(!file)return;
  try{if(file.size>20000000)throw new Error('Záloha je příliš velká (maximum 20 MB).');const wrapper=JSON.parse(await file.text());if(wrapper.format!=='pubbizz.pos.backup.v1')throw new Error('Tohle není záloha PUB-BIZZ.');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(wrapper.data))))).map(x=>x.toString(16).padStart(2,'0')).join('');if(hash!==wrapper.hash)throw new Error('Kontrolní součet nesedí. Soubor je změněný nebo poškozený.');C.validate(wrapper.data);showDialog('Obnovit pokladnu',`<p class="help">Záloha: <strong>${E(wrapper.data.settings.venue)}</strong><br>${wrapper.data.receipts.length} dokladů · ${wrapper.data.products.length} položek.<br>Po obnově používej pouze toto zařízení.</p>`,async()=>{const r=await Store.restore(wrapper.data);state=r.state;current='bar';render();},'Obnovit zálohu',()=>toast('Záloha byla obnovená.'));}catch(err){toast(err.message,true);}
});
window.addEventListener('online',connection);window.addEventListener('offline',connection);
async function refresh(){if(state){try{const next=await Store.read();if(next.revision!==state.revision){state=next;render();}}catch{toast('Nepodařilo se načíst uložená data.',true);}}}
window.addEventListener('focus',refresh);
(async()=>{
  try{state=await Store.open(refresh);C.validate(state);render();connection();
    if(document.documentElement.dataset.standalone){$('#offline-status').textContent='Samostatná offline verze · data tohoto prohlížeče';}
    else if('serviceWorker' in navigator){try{await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;$('#offline-status').textContent='Připraveno i bez internetu · jedno zařízení';}catch{$('#offline-status').textContent='Offline spuštění není připravené · data zůstávají místní';}}
  }catch(e){$('#app').innerHTML=`<div class="panel"><h1>Pokladnu nelze otevřít</h1><p class="error">${E(e.message)}</p><p class="section-gap">Nic nemaž. Zkus běžné okno Chrome / Edge, nebo obnov stránku. Pokud máš zálohu, můžeš ji obnovit v novém profilu prohlížeče.</p></div>`;$('#save-state').textContent='Úložiště není dostupné';}
})();
