/* User-supplied Agnis price list. Excludes all 30 unpriced entries; Cuba libre 130 CZK as requested. */
(function(root){ const catalog = {
  "version": "ztraceny-2026-09-25-r3",
  "products": [
    {
      "id": "agnis-50",
      "sourceCode": "50",
      "name": "12 Radegast 0,3",
      "category": "Pivo",
      "serving": "",
      "price": 5000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-51",
      "sourceCode": "51",
      "name": "12 Radegast 0,5",
      "category": "Pivo",
      "serving": "",
      "price": 6500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-63",
      "sourceCode": "63",
      "name": "10° Radegast 0,3",
      "category": "Pivo",
      "serving": "",
      "price": 4200,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-56",
      "sourceCode": "56",
      "name": "10° Radegast 0,5",
      "category": "Pivo",
      "serving": "",
      "price": 4900,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-57",
      "sourceCode": "57",
      "name": "12 Pilsner Urquell 0,3",
      "category": "Pivo",
      "serving": "",
      "price": 5500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-58",
      "sourceCode": "58",
      "name": "12 Pilsner Urquell 0,5",
      "category": "Pivo",
      "serving": "",
      "price": 6900,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-61",
      "sourceCode": "61",
      "name": "Pivo nealko",
      "category": "Pivo",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-71",
      "sourceCode": "71",
      "name": "Corona MEXICO 0,33",
      "category": "Pivo",
      "serving": "",
      "price": 6900,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-83",
      "sourceCode": "83",
      "name": "Frisco 0,33",
      "category": "Pivo",
      "serving": "",
      "price": 5500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-501",
      "sourceCode": "501",
      "name": "Bílé víno rozlev 0,1",
      "category": "Víno",
      "serving": "",
      "price": 3500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-1001",
      "sourceCode": "1001",
      "name": "Cervené vino rozlev 0.1",
      "category": "Víno",
      "serving": "",
      "price": 3500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-1653",
      "sourceCode": "1653",
      "name": "Prosecco 1L čep",
      "category": "Víno",
      "serving": "",
      "price": 45000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-1654",
      "sourceCode": "1654",
      "name": "Prosecco vald. 0,1 čep",
      "category": "Víno",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-1657",
      "sourceCode": "1657",
      "name": "Bohemia sekt 0,75",
      "category": "Víno",
      "serving": "",
      "price": 35000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-1658",
      "sourceCode": "1658",
      "name": "Prosecco 0,75",
      "category": "Víno",
      "serving": "",
      "price": 35000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-1801",
      "sourceCode": "1801",
      "name": "Becherovka 0,04",
      "category": "Likéry",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-1802",
      "sourceCode": "1802",
      "name": "Lemond 0,04",
      "category": "Likéry",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-1803",
      "sourceCode": "1803",
      "name": "Fernet stock 0,04",
      "category": "Likéry",
      "serving": "",
      "price": 6000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-1804",
      "sourceCode": "1804",
      "name": "Fernet citrus 0,04",
      "category": "Likéry",
      "serving": "",
      "price": 6000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-1805",
      "sourceCode": "1805",
      "name": "Jagermeister 0,04",
      "category": "Likéry",
      "serving": "",
      "price": 6500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-1806",
      "sourceCode": "1806",
      "name": "Zelená 0,04",
      "category": "Likéry",
      "serving": "",
      "price": 5000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2302",
      "sourceCode": "2302",
      "name": "Gin Beefeater 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2303",
      "sourceCode": "2303",
      "name": "Gin Bombay 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 9500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2304",
      "sourceCode": "2304",
      "name": "Tequila stříbrná 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2305",
      "sourceCode": "2305",
      "name": "Tequila zlatá 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2306",
      "sourceCode": "2306",
      "name": "Hruškovice R. Jelinek 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2307",
      "sourceCode": "2307",
      "name": "Hruška zlatá 40% 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 9500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2308",
      "sourceCode": "2308",
      "name": "Slivovice bílá budík 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2309",
      "sourceCode": "2309",
      "name": "Gin Malfy 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 11000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2312",
      "sourceCode": "2312",
      "name": "Finlandia kokos 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2314",
      "sourceCode": "2314",
      "name": "Finlandia brusinka",
      "category": "Destiláty",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2315",
      "sourceCode": "2315",
      "name": "Finlandia vodka 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2316",
      "sourceCode": "2316",
      "name": "Gin Hendricks 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2317",
      "sourceCode": "2317",
      "name": "Absinth 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2318",
      "sourceCode": "2318",
      "name": "Vodka Nemiroff 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2319",
      "sourceCode": "2319",
      "name": "Gin Columbian White 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2320",
      "sourceCode": "2320",
      "name": "Beluga Noble 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 16000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2321",
      "sourceCode": "2321",
      "name": "Cabrito Reposado 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2322",
      "sourceCode": "2322",
      "name": "Patrón Reposado 0,041",
      "category": "Destiláty",
      "serving": "",
      "price": 16500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2323",
      "sourceCode": "2323",
      "name": "Gin Broker's 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2324",
      "sourceCode": "2324",
      "name": "Cabrito blanco 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2325",
      "sourceCode": "2325",
      "name": "Gin Beefeater PINK 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 8500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2326",
      "sourceCode": "2326",
      "name": "Hruškovice Williams 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2327",
      "sourceCode": "2327",
      "name": "OMG gin 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 14000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2328",
      "sourceCode": "2328",
      "name": "Gin Tanqueray 0,041",
      "category": "Destiláty",
      "serving": "",
      "price": 12000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2329",
      "sourceCode": "2329",
      "name": "Gin Gin 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 12500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2330",
      "sourceCode": "2330",
      "name": "Gin Beefeater Orange 0,041",
      "category": "Destiláty",
      "serving": "",
      "price": 8500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2331",
      "sourceCode": "2331",
      "name": "Jagermeister Scharf 0,041",
      "category": "Destiláty",
      "serving": "",
      "price": 6500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2332",
      "sourceCode": "2332",
      "name": "Vodka Botanical 0,041",
      "category": "Destiláty",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2333",
      "sourceCode": "2333",
      "name": "Gin Endorphin 0,041",
      "category": "Destiláty",
      "serving": "",
      "price": 14500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2334",
      "sourceCode": "2334",
      "name": "Gin Malfy Arancia 0,041",
      "category": "Destiláty",
      "serving": "",
      "price": 12000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2335",
      "sourceCode": "2335",
      "name": "Gin Malfy Limone 0,041",
      "category": "Destiláty",
      "serving": "",
      "price": 12000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2336",
      "sourceCode": "2336",
      "name": "Gin Opihr London 0,041",
      "category": "Destiláty",
      "serving": "",
      "price": 14000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2337",
      "sourceCode": "2337",
      "name": "Brugal anejo 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2338",
      "sourceCode": "2338",
      "name": "Highland park 12y 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 16000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2339",
      "sourceCode": "2339",
      "name": "Macallan 12y 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 35000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2340",
      "sourceCode": "2340",
      "name": "Famous groose 0,04",
      "category": "Destiláty",
      "serving": "",
      "price": 8000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2801",
      "sourceCode": "2801",
      "name": "Kraken black spiced 2y 0,041",
      "category": "Rumy",
      "serving": "",
      "price": 9500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2802",
      "sourceCode": "2802",
      "name": "Legendario elixir 7y 0,041",
      "category": "Rumy",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2803",
      "sourceCode": "2803",
      "name": "El Dorado 12 y 0,041",
      "category": "Rumy",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2804",
      "sourceCode": "2804",
      "name": "Don papa 7y 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 14000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2805",
      "sourceCode": "2805",
      "name": "Diplomatico 15y 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 16000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2806",
      "sourceCode": "2806",
      "name": "Pyrat XO 15y 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 14000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2807",
      "sourceCode": "2807",
      "name": "Zacapa 23y 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 18500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2808",
      "sourceCode": "2808",
      "name": "Plantation XO 20y 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 18500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2809",
      "sourceCode": "2809",
      "name": "Rum Havana 3y 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2810",
      "sourceCode": "2810",
      "name": "Rum Tuzemský 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 5500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2811",
      "sourceCode": "2811",
      "name": "Captain Morgan 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2812",
      "sourceCode": "2812",
      "name": "Bucanero rum 7y 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 8000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2813",
      "sourceCode": "2813",
      "name": "Bacardi spiced 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2814",
      "sourceCode": "2814",
      "name": "Bacardi 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2815",
      "sourceCode": "2815",
      "name": "Malibu 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2816",
      "sourceCode": "2816",
      "name": "Havana Anos 7y 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2817",
      "sourceCode": "2817",
      "name": "Dictador 12y 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2818",
      "sourceCode": "2818",
      "name": "Rum santos Dumont 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 14000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2819",
      "sourceCode": "2819",
      "name": "Rum Angostura 7 Υ.0.0,04",
      "category": "Rumy",
      "serving": "",
      "price": 8000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2820",
      "sourceCode": "2820",
      "name": "Rum Angostura 1919 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 12000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2821",
      "sourceCode": "2821",
      "name": "Rum Republica 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 6500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2822",
      "sourceCode": "2822",
      "name": "Blue Mauritius 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 16500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2823",
      "sourceCode": "2823",
      "name": "Diplomatico 8yo 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2824",
      "sourceCode": "2824",
      "name": "Diplomatico Planas 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2825",
      "sourceCode": "2825",
      "name": "Morgan s colou",
      "category": "Rumy",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2826",
      "sourceCode": "2826",
      "name": "Morgan TIKI 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2827",
      "sourceCode": "2827",
      "name": "Don Papa Baroko",
      "category": "Rumy",
      "serving": "",
      "price": 15000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2828",
      "sourceCode": "2828",
      "name": "Heffron 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 6500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-2829",
      "sourceCode": "2829",
      "name": "Bumbu 0,04",
      "category": "Rumy",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3301",
      "sourceCode": "3301",
      "name": "Bushmills black bush 11y 0,041",
      "category": "Whisky",
      "serving": "",
      "price": 8000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3302",
      "sourceCode": "3302",
      "name": "Laphroaig 10y 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3303",
      "sourceCode": "3303",
      "name": "Jack Daniel's 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3304",
      "sourceCode": "3304",
      "name": "Jack D. Honey 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 9500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3305",
      "sourceCode": "3305",
      "name": "Tullamore Dew 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3306",
      "sourceCode": "3306",
      "name": "Jameson 3y 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3307",
      "sourceCode": "3307",
      "name": "Glenfarclas 12y 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3308",
      "sourceCode": "3308",
      "name": "Jack Daniel's Fire 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 9500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3309",
      "sourceCode": "3309",
      "name": "Jim Beam 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3310",
      "sourceCode": "3310",
      "name": "Ballantines 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3311",
      "sourceCode": "3311",
      "name": "Chivas Regal 12y 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 12000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3312",
      "sourceCode": "3312",
      "name": "Johnnie Walker Red Label 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3313",
      "sourceCode": "3313",
      "name": "Bushmills original 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3314",
      "sourceCode": "3314",
      "name": "J&B Rare 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3315",
      "sourceCode": "3315",
      "name": "Talisker 10 Y.0.0,04",
      "category": "Whisky",
      "serving": "",
      "price": 14500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3316",
      "sourceCode": "3316",
      "name": "Trebisch 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 16000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3317",
      "sourceCode": "3317",
      "name": "St.žitná Myslivecká reserva 0,041",
      "category": "Whisky",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3318",
      "sourceCode": "3318",
      "name": "Jack Daniels apple 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 9500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3319",
      "sourceCode": "3319",
      "name": "Jack Daniels Akce",
      "category": "Whisky",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3320",
      "sourceCode": "3320",
      "name": "Jack Daniels Fire Akce",
      "category": "Whisky",
      "serving": "",
      "price": 9500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3321",
      "sourceCode": "3321",
      "name": "Jack Daniels Honey Akce",
      "category": "Whisky",
      "serving": "",
      "price": 9500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3322",
      "sourceCode": "3322",
      "name": "Jack Daniels Apple Akce",
      "category": "Whisky",
      "serving": "",
      "price": 9500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3323",
      "sourceCode": "3323",
      "name": "Tullamore Honey 0,04",
      "category": "Whisky",
      "serving": "",
      "price": 8000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3400",
      "sourceCode": "3400",
      "name": "Martini 0,1",
      "category": "Víno",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3801",
      "sourceCode": "3801",
      "name": "Metaxa 5* 0,04",
      "category": "Brandy",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3802",
      "sourceCode": "3802",
      "name": "Godet Pearadise 0,02",
      "category": "Brandy",
      "serving": "",
      "price": 8000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-3805",
      "sourceCode": "3805",
      "name": "Gruzinak 0,04",
      "category": "Brandy",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4301",
      "sourceCode": "4301",
      "name": "Havana+Cola 0,3",
      "category": "Koktejly",
      "serving": "",
      "price": 12000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4302",
      "sourceCode": "4302",
      "name": "Mimosa",
      "category": "Koktejly",
      "serving": "",
      "price": 8000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4303",
      "sourceCode": "4303",
      "name": "Gin ton les plody",
      "category": "Koktejly",
      "serving": "",
      "price": 9500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4304",
      "sourceCode": "4304",
      "name": "Růžový Gin+tonic",
      "category": "Koktejly",
      "serving": "",
      "price": 10000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4305",
      "sourceCode": "4305",
      "name": "Limetkový Gin+tonic",
      "category": "Koktejly",
      "serving": "",
      "price": 10000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4306",
      "sourceCode": "4306",
      "name": "Gin tonik čerstvá okurka 0,31",
      "category": "Koktejly",
      "serving": "",
      "price": 10000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4307",
      "sourceCode": "4307",
      "name": "Jack Daniel's+Cola",
      "category": "Koktejly",
      "serving": "",
      "price": 10000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4308",
      "sourceCode": "4308",
      "name": "Morgan+Cola",
      "category": "Koktejly",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4309",
      "sourceCode": "4309",
      "name": "Gin+tonic 0,3",
      "category": "Koktejly",
      "serving": "",
      "price": 9500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4310",
      "sourceCode": "4310",
      "name": "Aperol Spritz",
      "category": "Koktejly",
      "serving": "",
      "price": 11500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4311",
      "sourceCode": "4311",
      "name": "Hugo spritz",
      "category": "Koktejly",
      "serving": "",
      "price": 11500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4312",
      "sourceCode": "4312",
      "name": "Mojito",
      "category": "Koktejly",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4313",
      "sourceCode": "4313",
      "name": "Chupito 0,04",
      "category": "Koktejly",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4322",
      "sourceCode": "4322",
      "name": "Finska brusinka zázvor",
      "category": "Koktejly",
      "serving": "",
      "price": 8000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4324",
      "sourceCode": "4324",
      "name": "Finlandia kokos cola",
      "category": "Koktejly",
      "serving": "",
      "price": 8000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4326",
      "sourceCode": "4326",
      "name": "Tequila sunrise 0,3",
      "category": "Koktejly",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4327",
      "sourceCode": "4327",
      "name": "Sex ve Ztracené 0,3",
      "category": "Koktejly",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4328",
      "sourceCode": "4328",
      "name": "Cuba libre 0,3",
      "category": "Koktejly",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4329",
      "sourceCode": "4329",
      "name": "Cosmopolitan 0,08",
      "category": "Koktejly",
      "serving": "",
      "price": 12000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4330",
      "sourceCode": "4330",
      "name": "Mojito nealko",
      "category": "Koktejly",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4331",
      "sourceCode": "4331",
      "name": "Vodka s džusem",
      "category": "Koktejly",
      "serving": "",
      "price": 9000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4332",
      "sourceCode": "4332",
      "name": "Piña colada",
      "category": "Koktejly",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4334",
      "sourceCode": "4334",
      "name": "Modrá laguna",
      "category": "Koktejly",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4335",
      "sourceCode": "4335",
      "name": "Malibu Orchid",
      "category": "Koktejly",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4336",
      "sourceCode": "4336",
      "name": "Cuba libre",
      "category": "Koktejly",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4337",
      "sourceCode": "4337",
      "name": "Mojito",
      "category": "Koktejly",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4338",
      "sourceCode": "4338",
      "name": "Sex ve Ztracené",
      "category": "Koktejly",
      "serving": "",
      "price": 13000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4343",
      "sourceCode": "4343",
      "name": "Skinny bitch",
      "category": "Koktejly",
      "serving": "",
      "price": 9500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4344",
      "sourceCode": "4344",
      "name": "Jack Daniel's Fire štrůdl",
      "category": "Koktejly",
      "serving": "",
      "price": 11000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4352",
      "sourceCode": "4352",
      "name": "HOUBA (ČVO,1+Cola0,1)",
      "category": "Koktejly",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4355",
      "sourceCode": "4355",
      "name": "Drink of the Day",
      "category": "Koktejly",
      "serving": "",
      "price": 9500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4553",
      "sourceCode": "4553",
      "name": "HeffronCola (0,1+0,1)",
      "category": "Koktejly",
      "serving": "",
      "price": 18000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4554",
      "sourceCode": "4554",
      "name": "SVIÑA 0,04",
      "category": "Koktejly",
      "serving": "",
      "price": 5500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4821",
      "sourceCode": "4821",
      "name": "Perlivá voda 0,33",
      "category": "Nealko",
      "serving": "",
      "price": 4000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4822",
      "sourceCode": "4822",
      "name": "Neperlivá voda 0,33",
      "category": "Nealko",
      "serving": "",
      "price": 4000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4823",
      "sourceCode": "4823",
      "name": "Coca-Cola 0,33",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4824",
      "sourceCode": "4824",
      "name": "Coca-Cola light 0,33",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4825",
      "sourceCode": "4825",
      "name": "Orangina 0,25",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4826",
      "sourceCode": "4826",
      "name": "Tonic 0,33",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4827",
      "sourceCode": "4827",
      "name": "Džus pomeranč 0,2",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4828",
      "sourceCode": "4828",
      "name": "Džus jahoda 0,2",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4829",
      "sourceCode": "4829",
      "name": "Džus jablko 0,2",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4830",
      "sourceCode": "4830",
      "name": "Red Bull 0,25",
      "category": "Nealko",
      "serving": "",
      "price": 8000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4831",
      "sourceCode": "4831",
      "name": "Kofola čep 0,5",
      "category": "Nealko",
      "serving": "",
      "price": 5500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4833",
      "sourceCode": "4833",
      "name": "Malina čep 0,4",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4836",
      "sourceCode": "4836",
      "name": "Jemně perlivá voda 0,33",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4837",
      "sourceCode": "4837",
      "name": "Mattoni Spritz 0,33",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4838",
      "sourceCode": "4838",
      "name": "Limetková limonáda 0,33",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4839",
      "sourceCode": "4839",
      "name": "Bonaqua 0,25",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4840",
      "sourceCode": "4840",
      "name": "Fanta 0,33",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4841",
      "sourceCode": "4841",
      "name": "Crodino 0,1",
      "category": "Nealko",
      "serving": "",
      "price": 6000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4842",
      "sourceCode": "4842",
      "name": "Voda s citronem 0,7",
      "category": "Nealko",
      "serving": "",
      "price": 5500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4843",
      "sourceCode": "4843",
      "name": "Kofola čep 0,3",
      "category": "Nealko",
      "serving": "",
      "price": 4000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4844",
      "sourceCode": "4844",
      "name": "Coca cola zero 0,25plech",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4845",
      "sourceCode": "4845",
      "name": "Coca cola zero 0,33",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4846",
      "sourceCode": "4846",
      "name": "Coca cola 0,1 gun",
      "category": "Nealko",
      "serving": "",
      "price": 1500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4847",
      "sourceCode": "4847",
      "name": "Tonik Ginger 0,33",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4848",
      "sourceCode": "4848",
      "name": "Sprite 0,33 plech",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4850",
      "sourceCode": "4850",
      "name": "Limonada čep 0,1",
      "category": "Nealko",
      "serving": "",
      "price": 1500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4852",
      "sourceCode": "4852",
      "name": "Fever water",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4853",
      "sourceCode": "4853",
      "name": "Kolkovné",
      "category": "Ostatní",
      "serving": "",
      "price": 50000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4854",
      "sourceCode": "4854",
      "name": "Tonik 0,1 gun",
      "category": "Nealko",
      "serving": "",
      "price": 1500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4855",
      "sourceCode": "4855",
      "name": "Džus rybíz 0,2",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4856",
      "sourceCode": "4856",
      "name": "Tonik růžový 0,33",
      "category": "Nealko",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4858",
      "sourceCode": "4858",
      "name": "Fanta 0,1 gun",
      "category": "Nealko",
      "serving": "",
      "price": 1500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4859",
      "sourceCode": "4859",
      "name": "Sprite 0,1 gun",
      "category": "Nealko",
      "serving": "",
      "price": 1500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4860",
      "sourceCode": "4860",
      "name": "Soda 0,1 gun",
      "category": "Nealko",
      "serving": "",
      "price": 1000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-4861",
      "sourceCode": "4861",
      "name": "Džus rozlev 0,1",
      "category": "Nealko",
      "serving": "",
      "price": 1500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5301",
      "sourceCode": "5301",
      "name": "Espresso Lungo",
      "category": "Teplé nápoje",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5302",
      "sourceCode": "5302",
      "name": "Espresso",
      "category": "Teplé nápoje",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5303",
      "sourceCode": "5303",
      "name": "Caffé ristretto",
      "category": "Teplé nápoje",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5304",
      "sourceCode": "5304",
      "name": "Turecká káva",
      "category": "Teplé nápoje",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5308",
      "sourceCode": "5308",
      "name": "Čaj",
      "category": "Teplé nápoje",
      "serving": "",
      "price": 5500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5309",
      "sourceCode": "5309",
      "name": "Zázvorový čaj čerstvý",
      "category": "Teplé nápoje",
      "serving": "",
      "price": 5500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5311",
      "sourceCode": "5311",
      "name": "Grog",
      "category": "Teplé nápoje",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5312",
      "sourceCode": "5312",
      "name": "Rioba čaj",
      "category": "Teplé nápoje",
      "serving": "",
      "price": 5500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5313",
      "sourceCode": "5313",
      "name": "Latte macchiato kokos",
      "category": "Teplé nápoje",
      "serving": "",
      "price": 7000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5314",
      "sourceCode": "5314",
      "name": "Hot capitan a džus",
      "category": "Teplé nápoje",
      "serving": "",
      "price": 8000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5315",
      "sourceCode": "5315",
      "name": "Svařák",
      "category": "Teplé nápoje",
      "serving": "",
      "price": 6000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5751",
      "sourceCode": "5751",
      "name": "Lahev Republica 0,7L",
      "category": "Rumy",
      "serving": "",
      "price": 105000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5801",
      "sourceCode": "5801",
      "name": "Brambůrky solené",
      "category": "Snacks",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5802",
      "sourceCode": "5802",
      "name": "Brambůrky česnekové",
      "category": "Snacks",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5803",
      "sourceCode": "5803",
      "name": "Snack",
      "category": "Snacks",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5804",
      "sourceCode": "5804",
      "name": "Arašídy KK",
      "category": "Snacks",
      "serving": "",
      "price": 5500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5807",
      "sourceCode": "5807",
      "name": "Brambůrky hořčicové",
      "category": "Snacks",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5809",
      "sourceCode": "5809",
      "name": "Tyčinky pekařské",
      "category": "Snacks",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5810",
      "sourceCode": "5810",
      "name": "ZIGI oříšky",
      "category": "Snacks",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5811",
      "sourceCode": "5811",
      "name": "Havlikovi tyčinky sýrové",
      "category": "Snacks",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5812",
      "sourceCode": "5812",
      "name": "Hradecké tyčinky",
      "category": "Snacks",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5816",
      "sourceCode": "5816",
      "name": "Guláš",
      "category": "Snacks",
      "serving": "",
      "price": 10000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5817",
      "sourceCode": "5817",
      "name": "Obložená mísa",
      "category": "Snacks",
      "serving": "",
      "price": 90000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5818",
      "sourceCode": "5818",
      "name": "Cibulové kroužky",
      "category": "Snacks",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5819",
      "sourceCode": "5819",
      "name": "Křupky",
      "category": "Snacks",
      "serving": "",
      "price": 4000,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5820",
      "sourceCode": "5820",
      "name": "Tyčinky",
      "category": "Snacks",
      "serving": "",
      "price": 4500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    },
    {
      "id": "agnis-5821",
      "sourceCode": "5821",
      "name": "HOT DOG",
      "category": "Snacks",
      "serving": "",
      "price": 9500,
      "vatRate": null,
      "active": true,
      "stockProductId": "",
      "priceNote": ""
    }
  ]
}; if(typeof module!=="undefined") module.exports=catalog; else root.POSCatalog=catalog; })(globalThis);
