'use strict';

(function () {
  let ctx = null;
  let products = [];
  let rows = [];
  let fingerprint = null;
  let sourceFileName = null;
  const $ = id => document.getElementById(id);
  const db = () => window.PubGuruBackend.client;
  const n = v => { const x = Number(String(v ?? '').replace(/\s/g,'').replace(',','.')); return Number.isFinite(x) ? x : 0; };
  const esc = v => String(v ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const today = () => new Date().toISOString().slice(0,10);
  const uid = () => `line_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;

  function toast(message, ms=4500){ const el=$('toast'); el.textContent=message; el.classList.remove('hidden'); clearTimeout(toast.t); toast.t=setTimeout(()=>el.classList.add('hidden'),ms); }

  async function sha256(file){ const hash=await crypto.subtle.digest('SHA-256',await file.arrayBuffer()); return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join(''); }

  function normalizeWords(text){ return String(text||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(w=>w.length>1); }
  function similarity(a,b){ const A=new Set(normalizeWords(a)),B=new Set(normalizeWords(b)); if(!A.size||!B.size)return 0; return [...A].filter(w=>B.has(w)).length/Math.max(A.size,B.size); }
  function bestProductMatch(text){ let best=null,score=0; for(const p of products){ const s=Math.max(similarity(text,p.name),...(p.aliases||[]).map(a=>similarity(text,a))); if(s>score){score=s;best=p;} } return score>=0.38?best:null; }

  function productOptions(selected=''){ return '<option value="">Bez párování</option>'+products.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${esc(p.name)}${p.ean?` · ${esc(p.ean)}`:''}${p.volume_ml?` · ${n(p.volume_ml)} ml`:''}</option>`).join(''); }

  function render(){ $('lineCount').textContent=String(rows.length); $('lines').innerHTML=rows.length?rows.map((r,i)=>`<div class="line" data-i="${i}"><label class="raw">Text z faktury<input class="rawName" value="${esc(r.rawName)}" /></label><label class="product">Produkt<select class="productId">${productOptions(r.productId)}</select></label><label>Ks<input class="qty" type="number" min="0" step="0.01" value="${r.qty||''}" /></label><label>Cena/ks<input class="price" type="number" min="0" step="0.01" value="${r.price||''}" /></label><button class="icon-btn remove" title="Odstranit">×</button></div>`).join(''):'<div class="mutedbox">OCR zatím nenašlo položky. Můžeš je přidat ručně.</div>';
    document.querySelectorAll('.line').forEach(el=>{ const i=Number(el.dataset.i); el.querySelector('.rawName').oninput=e=>rows[i].rawName=e.target.value; el.querySelector('.productId').onchange=e=>rows[i].productId=e.target.value; el.querySelector('.qty').oninput=e=>rows[i].qty=n(e.target.value); el.querySelector('.price').oninput=e=>rows[i].price=n(e.target.value); el.querySelector('.remove').onclick=()=>{rows.splice(i,1);render();}; }); }

  function parseDate(text){ const m=String(text||'').match(/(?:datum vystavení|vystaveno|datum)\s*[:\-]?\s*(\d{1,2}[.\/-]\d{1,2}[.\/-]\d{2,4})/i); if(!m)return null; const p=m[1].split(/[.\/-]/).map(Number); const y=p[2]<100?2000+p[2]:p[2]; return `${y}-${String(p[1]).padStart(2,'0')}-${String(p[0]).padStart(2,'0')}`; }

  function parseText(){ const text=$('ocrText').value||''; if(!text.trim())return toast('Nejdřív načti fakturu.'); const invoiceNo=text.match(/(?:faktura|daňový doklad|doklad)\s*(?:č\.?|číslo|no\.?|#)?\s*[:\-]?\s*([A-Z0-9\-/]{4,})/i); if(invoiceNo)$('number').value=invoiceNo[1]; const d=parseDate(text); if(d)$('date').value=d;
    const ignored=/(celkem|dph|základ|zaklad|splatnost|odběratel|dodavatel|ičo|dic|bankovní|variabilní|faktura)/i;
    const found=[]; for(const line of text.split(/\r?\n/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean)){ if(line.length<5||ignored.test(line)||!/[A-Za-zÁ-ž]/.test(line))continue; const nums=[...line.matchAll(/-?\d+(?:[ .]\d{3})*(?:[,.]\d{1,2})?/g)]; if(!nums.length)continue; const qtyUnit=line.match(/(\d+(?:[,.]\d+)?)\s*(ks|kus|bal|kart|láh|lah|btl)\b/i); const qty=qtyUnit?n(qtyUnit[1]):1; const price=n(nums[nums.length-1][0]); const idx=nums[0].index??line.length; let raw=line.slice(0,idx).replace(/[|;:]+$/g,'').trim(); if(raw.length<3)continue; const p=bestProductMatch(raw); found.push({id:uid(),rawName:raw,productId:p?.id||'',qty,price}); }
    rows=found.slice(0,80); render(); toast(rows.length?`Nalezeno ${rows.length} položek. Zkontroluj je.`:'Položky se nepodařilo bezpečně rozdělit. Přidej je ručně.'); }

  async function recognizeCanvas(canvas,label=''){ if(!window.Tesseract)throw new Error('OCR knihovna se nenačetla.'); const result=await Tesseract.recognize(canvas,'ces+eng',{logger:m=>{ if(m.status)$('ocrStatus').textContent=`${label}${m.status}`; if(typeof m.progress==='number')$('ocrProgress').style.width=`${Math.round(m.progress*100)}%`; }}); return result.data.text; }

  async function handleFile(file){ fingerprint=await sha256(file); sourceFileName=file.name||'invoice'; const dup=await db().from('invoices').select('id,invoice_number,status').eq('organization_id',ctx.organization.id).eq('source_fingerprint',fingerprint).maybeSingle(); if(dup.error)throw dup.error; if(dup.data){ $('duplicateBadge').textContent='duplicitní'; $('duplicateBadge').className='badge danger'; toast(`Tato faktura už existuje${dup.data.invoice_number?` (${dup.data.invoice_number})`:''}.`,5500); return; } $('duplicateBadge').textContent='nový doklad'; $('duplicateBadge').className='badge muted'; $('ocrProgressWrap').classList.remove('hidden'); $('ocrProgress').style.width='5%'; let text=''; const canvas=$('invoicePreview');
    if(file.type==='application/pdf'){ if(!window.pdfjsLib)throw new Error('PDF knihovna se nenačetla.'); pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'; const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise; const max=Math.min(pdf.numPages,4); for(let i=1;i<=max;i++){ const page=await pdf.getPage(i),vp=page.getViewport({scale:2}); canvas.width=vp.width; canvas.height=vp.height; canvas.classList.remove('hidden'); await page.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise; text+=`\n--- STRANA ${i} ---\n${await recognizeCanvas(canvas,`Strana ${i}: `)}`; } } else { const image=new Image(); const url=URL.createObjectURL(file); image.src=url; await image.decode(); const scale=Math.min(1,1800/image.naturalWidth); canvas.width=Math.round(image.naturalWidth*scale); canvas.height=Math.round(image.naturalHeight*scale); canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height); canvas.classList.remove('hidden'); URL.revokeObjectURL(url); text=await recognizeCanvas(canvas); }
    $('ocrText').value=text.trim(); $('ocrStatus').textContent='OCR dokončeno.'; $('ocrProgress').style.width='100%'; parseText(); }

  async function submit(){ if(!rows.length&&!$('ocrText').value.trim())return toast('Doklad nemá žádná data.'); const dup=fingerprint?await db().from('invoices').select('id').eq('organization_id',ctx.organization.id).eq('source_fingerprint',fingerprint).maybeSingle():{data:null,error:null}; if(dup.error)throw dup.error; if(dup.data)return toast('Tato faktura už je v databázi.',5000); const total=rows.reduce((s,r)=>s+n(r.qty)*n(r.price),0); const ins=await db().from('invoices').insert({organization_id:ctx.organization.id,venue_id:ctx.venue.id,supplier_name:$('supplier').value.trim(),invoice_number:$('number').value.trim(),issue_date:$('date').value||today(),total_amount:total||null,source_fingerprint:fingerprint,source_file_name:sourceFileName,raw_extraction:{raw_text:$('ocrText').value,source:'invoice_capture_v1',captured_role:ctx.role},extraction_provider:'tesseract-browser',status:'review',created_by:ctx.user.id}).select('id').single(); if(ins.error)throw ins.error;
    for(const r of rows){ const line=await db().from('invoice_lines').insert({invoice_id:ins.data.id,organization_id:ctx.organization.id,raw_name:r.rawName,product_id:r.productId||null,quantity:n(r.qty)||null,unit:'ks',unit_price:n(r.price)||null,line_total:n(r.qty)&&n(r.price)?n(r.qty)*n(r.price):null,match_method:r.productId?'capture_suggested_mapping':null,match_confidence:r.productId?0.8:null,status:'review',original_values:{raw_name:r.rawName}}); if(line.error)throw line.error; }
    const audit=await db().from('audit_events').insert({organization_id:ctx.organization.id,venue_id:ctx.venue.id,actor_user_id:ctx.user.id,event_type:'invoice.captured_for_review',entity_type:'invoice',entity_id:ins.data.id,after_data:{supplier:$('supplier').value.trim(),invoice_number:$('number').value.trim(),captured_lines:rows.length,total}}); if(audit.error)throw audit.error; toast(ctx.role==='staff'?'Faktura odeslána vedoucímu ke schválení.':'Faktura připravena ke schválení.',6000); if(['owner','manager'].includes(ctx.role))setTimeout(()=>location.href='invoice-review.html',700); else clear(); }

  function clear(){ rows=[]; fingerprint=null; sourceFileName=null; $('invoiceFile').value=''; $('ocrText').value=''; $('supplier').value=''; $('number').value=''; $('date').value=today(); $('invoicePreview').classList.add('hidden'); $('ocrProgressWrap').classList.add('hidden'); $('duplicateBadge').textContent='nový doklad'; $('duplicateBadge').className='badge muted'; render(); }

  async function init(){ ctx=await window.PubGuruBackend.loadContext(); if(!ctx?.user||!ctx?.organization||!ctx?.venue){location.replace('start.html');return;} $('roleBadge').textContent=ctx.role==='owner'?'Majitel':ctx.role==='manager'?'Vedoucí':'Zaměstnanec'; const p=await db().from('products').select('id,name,ean,volume_ml,aliases').eq('organization_id',ctx.organization.id).is('archived_at',null).order('name'); if(p.error)throw p.error; products=p.data||[]; $('date').value=today(); $('invoiceFile').onchange=e=>{const f=e.target.files?.[0];if(f)handleFile(f).catch(err=>{console.error(err);toast(`OCR selhalo: ${err.message}`,6500);});}; $('parseBtn').onclick=parseText; $('clearBtn').onclick=clear; $('addLineBtn').onclick=()=>{rows.push({id:uid(),rawName:'',productId:'',qty:1,price:0});render();}; $('submitBtn').onclick=()=>submit().catch(err=>{console.error(err);toast(`Uložení selhalo: ${err.message}`,7000);}); render(); }
  document.addEventListener('DOMContentLoaded',()=>init().catch(err=>{console.error(err);toast(`Nelze spustit faktury: ${err.message}`,7000);}));
})();