'use strict';
(function(){
let ctx=null;
const db=()=>PubGuruBackend.client,$=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:0};
const money=v=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:2}).format(n(v));
function toast(m,ms=4500){const e=$('toast');e.textContent=m;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),ms)}
function monthStart(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`}
function today(){return new Date().toISOString().slice(0,10)}
async function ensureRole(){ctx=await PubGuruBackend.loadContext();if(!ctx?.user||!ctx?.organization||!ctx?.venue){location.replace('start.html');return false}if(!['owner','manager'].includes(ctx.role)){location.replace('start.html');return false}$('roleBadge').textContent=ctx.role==='owner'?'Majitel':'Vedoucí';return true}
function paymentLabel(i){if(i.payment_status!=='paid')return i.payment_status==='unpaid'?'Nezaplaceno':'Neznámé';return i.payment_method==='card'?'Kartou':'Hotově'}
async function load(){const from=$('from').value,to=$('to').value,basis=$('basis').value,method=$('method').value,status=$('status').value;let q=db().from('invoices').select('id,supplier_name,invoice_number,issue_date,total_amount,total_amount_gross,payment_status,payment_method,paid_at,status,created_at').eq('organization_id',ctx.organization.id).eq('venue_id',ctx.venue.id).eq('status','approved');if(status==='paid')q=q.eq('payment_status','paid');else if(status==='unpaid')q=q.eq('payment_status','unpaid');if(method==='cash')q=q.eq('payment_status','paid').eq('payment_method','cash');if(method==='card')q=q.eq('payment_status','paid').eq('payment_method','card');if(from){q=basis==='paid_at'?q.gte('paid_at',`${from}T00:00:00`):q.gte('issue_date',from)}if(to){q=basis==='paid_at'?q.lte('paid_at',`${to}T23:59:59`):q.lte('issue_date',to)}q=q.order(basis==='paid_at'?'paid_at':'issue_date',{ascending:false}).limit(500);const r=await q;if(r.error)throw r.error;const rows=r.data||[];const sum=rows.reduce((s,i)=>s+n(i.total_amount_gross??i.total_amount),0);$('count').textContent=String(rows.length);$('sum').textContent=money(sum);$('results').innerHTML=rows.length?rows.map(i=>`<article class="invoice-row"><div><strong>${esc(i.supplier_name||'Bez dodavatele')}</strong><small>${esc(i.invoice_number||'bez čísla')}</small></div><div><span>${esc(i.issue_date||'')}</span><small>${i.paid_at?`uhrazeno ${esc(String(i.paid_at).slice(0,10))}`:'bez data úhrady'}</small></div><div><span class="pay ${i.payment_method==='card'?'card':'cash'}">${paymentLabel(i)}</span></div><div class="amount">${money(i.total_amount_gross??i.total_amount)}</div></article>`).join(''):'<div class="empty">V tomto období nejsou žádné odpovídající faktury.</div>'}
async function init(){if(!await ensureRole())return;$('from').value=monthStart();$('to').value=today();for(const id of ['from','to','basis','method','status'])$(id).onchange=()=>load().catch(e=>toast(e.message));$('refreshBtn').onclick=()=>load().catch(e=>toast(e.message));await load()}
document.addEventListener('DOMContentLoaded',()=>init().catch(e=>toast(`Historii nelze načíst: ${e.message}`,7000)));
})();